// src/GameList.js

export const GAME_PACKS = [
  {
    id: "bar",
    name: "Bar Games",
    description: "Quick, loud, competitive games for drinks and pub nights.",
    accent: "#f4c431",
  },
  {
    id: "restaurant",
    name: "Restaurant Games",
    description: "Short table-friendly games for meals and casual challenges.",
    accent: "#ff8a5b",
  },
  {
    id: "board",
    name: "Board Games",
    description: "Slightly longer tactical or movement-based games.",
    accent: "#7aa2ff",
  },
  {
    id: "casino",
    name: "Casino Games",
    description: "Card, dice, and chance-based games inspired by casino play.",
    accent: "#3bd17f",
  },
  {
    id: "reaction",
    name: "Reaction Games",
    description: "Fast, simple games based on timing and reflexes.",
    accent: "#ff5c5c",
  },
];

export const GAME_CATALOGUE = [
  {
    id: "sumo",
    name: "Sumo",
    pack: "bar",
    thumb: "/thumbs/sumo.png",
    description: "Push opponents out of the ring before time runs out.",
    minPlayers: 2,
    maxPlayers: 4,
    difficulty: "Easy",
    duration: "30–60 sec",
    energy: "High",
    typeLabel: "Arcade",
    defaultEnabled: true,
  },
  {
    id: "darts",
    name: "Darts",
    pack: "bar",
    thumb: "/thumbs/darts.png",
    description: "Aim, fire, and score as highly as possible.",
    minPlayers: 2,
    maxPlayers: 6,
    difficulty: "Easy",
    duration: "45–90 sec",
    energy: "Medium",
    typeLabel: "Precision",
    defaultEnabled: true,
  },
  {
    id: "guessing_card",
    name: "Guessing Card",
    pack: "restaurant",
    thumb: "/thumbs/guessing_card.png",
    description: "Lock in a card value closest to the final reveal.",
    minPlayers: 2,
    maxPlayers: 8,
    difficulty: "Medium",
    duration: "1–2 min",
    energy: "Low",
    typeLabel: "Mind Game",
    defaultEnabled: true,
  },
  {
    id: "maze",
    name: "Maze",
    pack: "board",
    thumb: "/thumbs/maze.png",
    description: "Navigate the maze and reach the centre first.",
    minPlayers: 2,
    maxPlayers: 4,
    difficulty: "Medium",
    duration: "1–3 min",
    energy: "Medium",
    typeLabel: "Tactical",
    defaultEnabled: true,
  },

  // NEW CASINO / CARD / DICE GAMES

  {
    id: "ninety_nine",
    name: "99",
    pack: "casino",
    thumb: "/thumbs/ninety_nine.png",
    description: "Play cards into a running total and try to push the score to 99.",
    minPlayers: 2,
    maxPlayers: 4,
    difficulty: "Medium",
    duration: "2–4 min",
    energy: "Low",
    typeLabel: "Card Game",
    defaultEnabled: false,
  },
  {
    id: "blackjack",
    name: "Blackjack",
    pack: "casino",
    thumb: "/thumbs/blackjack.png",
    description: "Beat the dealer by getting closer to 21 without going bust.",
    minPlayers: 1,
    maxPlayers: 4,
    difficulty: "Medium",
    duration: "2–5 min",
    energy: "Low",
    typeLabel: "Card Game",
    defaultEnabled: false,
  },
  {
    id: "craps",
    name: "Craps",
    pack: "casino",
    thumb: "/thumbs/craps.png",
    description: "Roll two dice and compete for the highest total.",
    minPlayers: 1,
    maxPlayers: 4,
    difficulty: "Easy",
    duration: "30–60 sec",
    energy: "Low",
    typeLabel: "Dice",
    defaultEnabled: false,
  },
  {
    id: "poker",
    name: "5-Card Draw Poker",
    pack: "casino",
    thumb: "/thumbs/poker.png",
    description: "Draw, bet, fold, and reveal the strongest poker hand.",
    minPlayers: 2,
    maxPlayers: 4,
    difficulty: "Hard",
    duration: "3–6 min",
    energy: "Low",
    typeLabel: "Card Game",
    defaultEnabled: false,
  },

  // NEW REACTION / QUICK GAMES

  {
    id: "button_masher",
    name: "Button Masher",
    pack: "reaction",
    thumb: "/thumbs/button_masher.png",
    description: "Mash the button as fast as possible before the timer ends.",
    minPlayers: 1,
    maxPlayers: 8,
    difficulty: "Easy",
    duration: "10–20 sec",
    energy: "High",
    typeLabel: "Reaction",
    defaultEnabled: false,
  },
  {
    id: "stack",
    name: "Stack",
    pack: "reaction",
    thumb: "/thumbs/stack.png",
    description: "Tap with precision to build the tallest tower.",
    minPlayers: 1,
    maxPlayers: 4,
    difficulty: "Medium",
    duration: "45–90 sec",
    energy: "Medium",
    typeLabel: "Timing",
    defaultEnabled: false,
  },

  // EXISTING FUTURE / LOCKABLE GAMES

  {
    id: "dice_duel",
    name: "Dice Duel",
    pack: "bar",
    thumb: "/thumbs/dice_duel.png",
    description: "Roll against the group and let the highest number win.",
    minPlayers: 2,
    maxPlayers: 8,
    difficulty: "Easy",
    duration: "20–40 sec",
    energy: "Low",
    typeLabel: "RNG",
    defaultEnabled: false,
  },
  {
    id: "stack_attack",
    name: "Stack Attack",
    pack: "reaction",
    thumb: "/thumbs/stack_attack.png",
    description: "Time your actions and build the highest stack.",
    minPlayers: 2,
    maxPlayers: 4,
    difficulty: "Medium",
    duration: "45–90 sec",
    energy: "Medium",
    typeLabel: "Reaction",
    defaultEnabled: false,
  },
  {
    id: "quickdraw",
    name: "QuickDraw",
    pack: "reaction",
    thumb: "/thumbs/quickdraw.png",
    description: "React first when the signal appears.",
    minPlayers: 2,
    maxPlayers: 8,
    difficulty: "Easy",
    duration: "20–40 sec",
    energy: "High",
    typeLabel: "Reaction",
    defaultEnabled: false,
  },
  {
    id: "roulette",
    name: "Roulette",
    pack: "casino",
    thumb: "/thumbs/roulette.png",
    description: "A fast chance-based round for quick outcomes.",
    minPlayers: 2,
    maxPlayers: 8,
    difficulty: "Easy",
    duration: "20–40 sec",
    energy: "Low",
    typeLabel: "Chance",
    defaultEnabled: false,
  },
];

export const PACK_LOOKUP = Object.fromEntries(
  GAME_PACKS.map((pack) => [pack.id, pack])
);

export const GAME_LIST = GAME_CATALOGUE.map((g) => ({
  id: g.id,
  name: g.name,
  enabled: g.defaultEnabled,
}));