export const GAME_PACKS = [
  {
    id: "bar",
    name: "Bar Games",
    description: "Quick, loud, competitive games for drinks and pub nights.",
    accent: "#f4c431",
  },
  {
    id: "restaurant",
    name: "Restaurant Games",
    description: "Short table-friendly games for meals and casual challenges.",
    accent: "#ff8a5b",
  },
  {
    id: "board",
    name: "Board Games",
    description: "Slightly longer tactical or movement-based games.",
    accent: "#7aa2ff",
  },
];

export const GAME_CATALOGUE = [
  {
    id: "sumo",
    name: "Sumo",
    pack: "bar",
    thumb: "/thumbs/sumo.png",
    description: "Push opponents out of the ring before time runs out.",
    minPlayers: 2,
    maxPlayers: 4,
    difficulty: "Easy",
    duration: "30–60 sec",
    energy: "High",
    typeLabel: "Arcade",
    defaultEnabled: true,
  },
  {
    id: "darts",
    name: "Darts",
    pack: "bar",
    thumb: "/thumbs/darts.png",
    description: "Aim, fire, and score as highly as possible.",
    minPlayers: 2,
    maxPlayers: 6,
    difficulty: "Easy",
    duration: "45–90 sec",
    energy: "Medium",
    typeLabel: "Precision",
    defaultEnabled: true,
  },
  {
    id: "guessing_card",
    name: "Guessing Card",
    pack: "restaurant",
    thumb: "/thumbs/guessing_card.png",
    description: "Lock in a card value closest to the final reveal.",
    minPlayers: 2,
    maxPlayers: 8,
    difficulty: "Medium",
    duration: "1–2 min",
    energy: "Low",
    typeLabel: "Mind Game",
    defaultEnabled: true,
  },
  {
    id: "maze",
    name: "Maze",
    pack: "board",
    thumb: "/thumbs/maze.png",
    description: "Navigate the maze and reach the centre first.",
    minPlayers: 2,
    maxPlayers: 4,
    difficulty: "Medium",
    duration: "1–3 min",
    energy: "Medium",
    typeLabel: "Tactical",
    defaultEnabled: true,
  },

  // ✅ STACK
  {
    id: "stack",
    name: "Stack",
    pack: "restaurant",
    thumb: "/thumbs/stack.png",
    description: "Time your taps to build the tallest tower.",
    minPlayers: 1,
    maxPlayers: 4,
    difficulty: "Medium",
    duration: "45–90 sec",
    energy: "Medium",
    typeLabel: "Reaction",
    defaultEnabled: true,
  },

  // ✅ NEW GAMES
  {
    id: "poker",
    name: "Poker",
    pack: "restaurant",
    thumb: "/thumbs/poker.png",
    description: "Play a quick poker-style round and beat the table.",
    minPlayers: 2,
    maxPlayers: 8,
    difficulty: "Medium",
    duration: "1–3 min",
    energy: "Low",
    typeLabel: "Card Game",
    defaultEnabled: true,
  },
  {
    id: "ninety_nine",
    name: "Ninety Nine",
    pack: "bar",
    thumb: "/thumbs/ninety_nine.png",
    description: "Count carefully and avoid pushing the total too far.",
    minPlayers: 2,
    maxPlayers: 8,
    difficulty: "Medium",
    duration: "1–3 min",
    energy: "Medium",
    typeLabel: "Card Game",
    defaultEnabled: true,
  },
  {
    id: "craps",
    name: "Craps",
    pack: "bar",
    thumb: "/thumbs/craps.png",
    description: "Roll the dice and chase the winning outcome.",
    minPlayers: 2,
    maxPlayers: 8,
    difficulty: "Easy",
    duration: "30–90 sec",
    energy: "Medium",
    typeLabel: "Dice",
    defaultEnabled: true,
  },
  {
    id: "button_masher",
    name: "Button Masher",
    pack: "bar",
    thumb: "/thumbs/button_masher.png",
    description: "Mash as fast as possible before the timer runs out.",
    minPlayers: 1,
    maxPlayers: 8,
    difficulty: "Easy",
    duration: "20–40 sec",
    energy: "High",
    typeLabel: "Reaction",
    defaultEnabled: true,
  },
  {
    id: "blackjack",
    name: "Blackjack",
    pack: "restaurant",
    thumb: "/thumbs/blackjack.png",
    description: "Get close to 21 without going bust.",
    minPlayers: 1,
    maxPlayers: 8,
    difficulty: "Medium",
    duration: "1–3 min",
    energy: "Low",
    typeLabel: "Card Game",
    defaultEnabled: true,
  },

  // 🔒 Locked ones (unchanged)
  {
    id: "dice_duel",
    name: "Dice Duel",
    pack: "bar",
    thumb: "/thumbs/dice_duel.png",
    description: "Roll against the group and let the highest number win.",
    minPlayers: 2,
    maxPlayers: 8,
    difficulty: "Easy",
    duration: "20–40 sec",
    energy: "Low",
    typeLabel: "RNG",
    defaultEnabled: false,
  },
  {
    id: "quickdraw",
    name: "QuickDraw",
    pack: "bar",
    thumb: "/thumbs/quickdraw.png",
    description: "React first when the signal appears.",
    minPlayers: 2,
    maxPlayers: 8,
    difficulty: "Easy",
    duration: "20–40 sec",
    energy: "High",
    typeLabel: "Reaction",
    defaultEnabled: false,
  },
  {
    id: "roulette",
    name: "Roulette",
    pack: "restaurant",
    thumb: "/thumbs/roulette.png",
    description: "A fast chance-based round for quick outcomes.",
    minPlayers: 2,
    maxPlayers: 8,
    difficulty: "Easy",
    duration: "20–40 sec",
    energy: "Low",
    typeLabel: "Chance",
    defaultEnabled: false,
  },
];

export const PACK_LOOKUP = Object.fromEntries(
  GAME_PACKS.map((pack) => [pack.id, pack])
);

export const GAME_LIST = GAME_CATALOGUE.map((g) => ({
  id: g.id,
  name: g.name,
  enabled: g.defaultEnabled,
}));